FROM debian:bullseye-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    libstdc++6 \
    libc6 \
    libgcc-s1 \
    libx11-6 \
    libglu1 \
    libpulse0 \
    libasound2 \
    libxcursor1 \
    libxi6 \
    libxrandr2 \
    libxss1 \
    libxtst6 \
    libxxf86vm1 \
    bash \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./GameServerBuild/ /app/
RUN chmod +x /app/buildServer.x86_64

ENV GAME_PORT=7777
ENV XDG_RUNTIME_DIR=/tmp
EXPOSE ${GAME_PORT}

CMD ["sh", "-c", "./buildServer.x86_64 -batchmode -nographics -port $GAME_PORT"]